apiVersion: apps/v1
kind: Deployment
metadata:
  name: ralparque
spec:
  selector:
    matchLabels:
      app: ralparque
  replicas: 1
  template:
    metadata:
      labels:
        app: ralparque
    spec:
      containers:
      - name: organizador
        image: organizador:latest
        ports:
        - containerPort: 8080
    

