version: "3"
networks:
  simon_bolivar:
    external: false
services:
  mana:
    image: artista
    container_name: mana
    networks:
      - simon_bolivar
    restart: always
    ports:
        - "9991:22"
  
  aterciopelados:
    image: artista
    container_name: aterciopelados
    networks:
      - simon_bolivar
    restart: always
    ports:
      - "9992:22"
      
  fabulosos_cadillacs:
    image: artista
    container_name: fabulosos_cadillacs9
    networks:
      - simon_bolivar
    restart: always
    ports:
      - "9993:22"
      
  organizador:
    image: organizador
    container_name: organizador
    networks:
      - simon_bolivar
    restart: always
    ports:
      - "9994:22"